import { MenuItem } from '../models/menu.model';

const MENU_ITEMS_INS_PRODUCTS_OPERATOR_TOP_LEVEL: MenuItem[] = [
    {
        key: 'operator',
        label: 'Operator Menu',
        labelHE: 'תפריט מפעיל',
        isTitle: true,
        show: true,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "all"
    },
    {
        key: 'operator-home',
        label: 'Home',
        labelHE: 'בית',
        isTitle: false,
        icon: 'fas fa-home',
        // icon: 'fe-airplay',
        link: '/operator/dashboard',
        // parentKey: null,
        show: true,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "all",
    },
    {
        key: 'operator-console',
        label: 'Operator Console',
        labelHE: 'קונסולת מפעיל',
        isTitle: false,
        icon: 'dripicons dripicons-toggles',
        link: '/operator/console',
        // parentKey: null,
        show: false,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "all",
    },
    {
        key: 'operator-users',
        label: 'Clients',
        labelHE: 'לקוחות ומשתמשים',
        isTitle: false,
        icon: 'dripicons dripicons-user-group',
        link: '/operator/clients-and-users',
        // parentKey: null,
        show: true,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "all",
    },
    {
        key: 'operator-administration-requests-administrative-onboarding',
        label: 'Requests',
        labelHE: 'אונבורדינג',
        icon: 'fas fa-concierge-bell',
        isTitle: false,
        link: '/operator/requests-and-quotes/requests-all',
        collapsed: true,
        // parentKey: 'operator-administration-requests-administrative',
        show: true,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "all",
    },
    {
        key: 'operator-payton-demo-analysis-core',
        label: 'Core',
        labelHE: 'שארית ביניים',
        icon: 'fe-bar-chart-2',
        link: '/operator/payton-demo/core',
        show: false,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "securitization",
    },

]

const MENU_ITEMS_INS_PRODUCTS_OPERATOR_PRODUCT_MANAGEMENT: MenuItem[] = [
    {
        key: 'operator-products-management',
        label: 'Products',
        labelHE: 'מוצרים וחשבונות',
        isTitle: false,
        collapsed: true,
        icon: 'dripicons dripicons-cart',
        show: true,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "wallet",
        // link: '/operator/dashboard',
        children: [
            {
                key: 'operator-products-and-accounts-products',
                label: 'Product Dashboard',
                labelHE: 'מוצרים',
                // icon: 'dripicons dripicons-cart',
                icon: 'fe-airplay',
                link: '/operator/platform-accounts/product-management',
                // parentKey: 'operator-products-and-accounts',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "wallet",
            },
            {
                key: 'operator-products-management-wallets',
                label: 'Cash Manager',
                labelHE: 'מוצרים',
                icon: 'fas fa-wallet noti-icon',
                link: '/operator/product-management/cash',
                parentKey: 'operator-products-management',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "wallet",
            },
            {
                key: 'operator-products-management-lending',
                label: 'Tokenized Loans',
                labelHE: 'מוצרים',
                icon: 'fas fa-hand-holding-usd',
                link: '/operator/product-management/tokenized-loans',
                parentKey: 'operator-products-management',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "assets",
            },
            {
                key: 'operator-products-management-p-notes',
                label: 'Syndications',
                labelHE: 'מוצרים',
                icon: 'dripicons dripicons-cart',
                link: '/operator/product-management/syndications',
                parentKey: 'operator-products-management',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "marketplace",
            },
            {
                key: 'operator-products-management-fund',
                label: 'Fund Manager',
                labelHE: 'מוצרים',
                icon: 'fe-bar-chart',
                link: '/operator/product-management/funds',
                parentKey: 'operator-products-management',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "fund",
            },
            {
                key: 'operator-products-management-securitization',
                label: 'Securitizations',
                labelHE: 'מוצרים',
                icon: 'dripicons dripicons-swap',
                link: '/operator/product-management/securitizations',
                parentKey: 'operator-products-management',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "securitization",
            },

            
            

        ]


    },
]

const MENU_ITEMS_INS_PRODUCTS_OPERATOR_CORE_ACCOUNTING: MenuItem[] = [
    {
        key: 'operator-products-and-accounts',
        label: 'Core Accounting',
        labelHE: 'מוצרים וחשבונות',
        isTitle: false,
        collapsed: true,
        icon: 'fas fa-university',
        show: true,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "wallet",
        // link: '/operator/dashboard',
        children: [
 
            {
                key: 'operator-products-and-accounts-accounting',
                label: 'Ledger',
                labelHE: 'חשבונות',
                icon: 'fas fa-balance-scale',
                link: '/operator/platform-accounts/core-accounting',
                // parentKey: 'operator-products-and-accounts',
                show: true,
                isInternal: true,
                isProduct: false,
                product: "wallet",
            },
            {
                key: 'operator-products-and-accounts-transactions',
                label: 'Transactions',
                labelHE: 'עסקאות',
                icon: 'dripicons dripicons-swap',
                link: '/operator/platform-accounts/transactions',
                // parentKey: 'operator-products-and-accounts',
                show: true,
                isInternal: true,
                isProduct: false,
                product: "wallet",
            },
            {
                key: 'operator-dlt-network',
                label: 'DLT Network Accounts',
                labelHE: 'מצב הרשת הבלוקצ׳יין DLT',
                icon: 'fas fa-bezier-curve',
                link: '/operator/platform-accounts/credit-network',
                parentKey: 'operator-credit-network',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",
            },
            {
                key: 'operator-dlt-network-corda',
                label: 'Blockchain Network',
                labelHE: 'מצב הרשת הבלוקצ׳יין DLT',
                icon: 'fas fa-link',
                link: '/operator/platform-accounts/blockchain',
                parentKey: 'operator-credit-network',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",
            },

        ]


    },
]

const MENU_ITEMS_INS_PRODUCTS_OPERATOR_FINANCIAL_ANALYTICS: MenuItem[] = [
   
    {
        key: 'operator-financial-analytics',
        label: 'Financial Analytics',
        labelHE: 'ניתוחים פיננסיים',
        isTitle: false,
        icon: 'fe-trending-up',
        link: '/operator/dashboard',
        show: true,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "assets",
        collapsed: true,
        children: [

            {
                key: 'operator-dlt-trust-position',
                label: 'All Token Positions',
                labelHE: 'עמדת קרן הנאמנות',
                icon: 'fe-percent',
                link: '/operator/platform-analytics/trust-position',
                parentKey: 'operator-credit-network',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "fund",
            },
            {
                key: 'operator-dlt-fund-position',
                label: 'Fund Position',
                labelHE: 'עמדת קרן ההשקעות',
                icon: 'fe-dollar-sign',
                link: '/operator/platform-analytics/fund-position',
                parentKey: 'operator-credit-network',
                show: false,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "fund",
            },
            {
                key: 'operator-dlt-e2e-network-allocations',
                label: 'Network Allocations',
                labelHE: 'הקצאות קצה-אל-קצה',
                link: '/operator/platform-analytics/end-to-end-allocations',
                icon: 'fe-hash',
                parentKey: 'operator-credit-network',
                show: false,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "fund",
            },


            {
                key: 'operator-financial-analytics-platform-analysis-dashboard',
                label: 'Operator Analyses',
                labelHE: 'ניתוחי מפעיל',
                icon: 'dripicons dripicons-graph-pie',
                link: '/operator/platform-analytics/network-platform-analyses',
                parentKey: 'operator-financial-analytics',
                show: false,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",
            },
            {
                key: 'operator-dlt-network-analysis-home',
                label: 'Cashflows Dashboard',
                labelHE: 'דַּשְׁבּוֹרְד אנליטיקה של הרשת',
                icon: 'fe-airplay',
                parentKey: 'operator-financial-analytics-platform-analysis',
                link: '/operator/platform-analytics/network-analysis-dashboard',
                // parentKey: 'operator-credit-network',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "assets",
            },

            {
                key: 'operator-financial-analytics-platform-analysis-network-assets',
                label: 'Tokenized Loans',
                labelHE: 'נכסים ברשת',
                icon: 'dripicons dripicons-network-3',
                link: '/operator/platform-analytics/tokenized-loans',
                parentKey: 'operator-financial-analytics-platform-analysis',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "assets",

            },

            {
                key: 'operator-financial-analytics-platform-analysis-p-note-funding',
                label: 'P-Note Funding',
                labelHE: 'מימון ע״י P-Notes',
                // icon: 'dripicons dripicons-graph-line',
                icon: 'fe-trending-up',
                link: '/operator/platform-analytics/p-note-funding',
                parentKey: 'operator-financial-analytics-platform-analysis',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "marketplace",
            },
            {
                key: 'operator-financial-analytics-platform-analysis-interim-residual',
                label: 'Interim Residual',
                labelHE: 'שארית ביניים',
                icon: 'fe-bar-chart-2',
                link: '/operator/platform-analytics/interim-residual-cashflow',
                parentKey: 'operator-financial-analytics-platform-analysis',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "securitization",
            },
            {
                key: 'operator-financial-analytics-platform-analysis-funds',
                label: 'Funds',
                labelHE: 'שארית ביניים',
                icon: 'fe-pie-chart',
                // link: '/operator/platform-analytics/claims/65f046885a4d3f772f4a8bd6/core',
                parentKey: 'operator-financial-analytics-platform-analysis',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                collapsed: true,
                product: "securitization",
                children:null
            },
            {
                key: 'operator-financial-analytics-platform-analysis-waterfall-structuring',
                label: 'Waterfall Structuring',
                labelHE: 'מבנה המפל',
                icon: 'dripicons dripicons-toggles',
                link: '/operator/platform-analytics/waterfall-structuring',
                parentKey: 'operator-financial-analytics-platform-analysis',
                show: false,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "securitization",
            },
            {
                key: 'operator-financial-analytics-platform-analysis-waterfall-structuring',
                label: 'Cashflow Structuring',
                labelHE: 'מבנה המפל',
                icon: 'dripicons dripicons-toggles',
                link: '/operator/platform-analytics/cashflow/65f0468a1fe00029e14b7cd4/securitization',
                parentKey: 'operator-financial-analytics-platform-analysis',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "securitization",
            },
            {
                key: 'operator-financial-analytics-platform-analysis',
                label: 'Network',
                labelHE: 'רשת',
                icon: 'dripicons dripicons-network-3',
                link: '/member/requests/loans',
                parentKey: 'operator-financial-analytics',
                collapsed: true,
                show: false,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "assets",
                children: [
                    {
                        key: 'operator-dlt-network-analysis-home',
                        label: 'Network Analyses',
                        labelHE: 'דַּשְׁבּוֹרְד אנליטיקה של הרשת',
                        icon: 'fe-airplay',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        link: '/operator/platform-analytics/network-analysis-dashboard',
                        // parentKey: 'operator-credit-network',
                        show: true,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "assets",
                    },
        
                    {
                        key: 'operator-financial-analytics-platform-analysis-network-assets',
                        label: 'Assets',
                        labelHE: 'נכסים ברשת',
                        icon: 'dripicons dripicons-network-3',
                        link: '/operator/platform-analytics/network-assets',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        show: true,
                        isInternal: true,
                        isMember: true,
                        isProduct: false,
                        product: "assets",

                    },

                    {
                        key: 'operator-financial-analytics-platform-analysis-p-note-funding',
                        label: 'P-Note Funding',
                        labelHE: 'מימון ע״י P-Notes',
                        // icon: 'dripicons dripicons-graph-line',
                        icon: 'fe-trending-up',
                        link: '/operator/platform-analytics/p-note-funding',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        show: true,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "marketplace",
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-interim-residual',
                        label: 'Interim Residual',
                        labelHE: 'שארית ביניים',
                        icon: 'fe-bar-chart-2',
                        link: '/operator/platform-analytics/interim-residual-cashflow',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        show: true,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "securitization",
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-waterfall-structuring',
                        label: 'Waterfall Structuring',
                        labelHE: 'מבנה המפל',
                        icon: 'dripicons dripicons-toggles',
                        link: '/operator/platform-analytics/waterfall-structuring',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        show: false,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "securitization",
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-waterfall-structuring',
                        label: 'Cashflow Structuring',
                        labelHE: 'מבנה המפל',
                        icon: 'dripicons dripicons-toggles',
                        link: '/operator/platform-analytics/cashflow/65f0468a1fe00029e14b7cd4/securitization',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        show: true,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "securitization",
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-s-note-funding',
                        label: 'S-Note Funding',
                        labelHE: 'מימון ע״י S-Notes',
                        icon: 'fe-bar-chart',
                        link: '/operator/platform-analytics/s-note-funding/summary',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        show: false,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "securitization",

                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-trust-position',
                        label: 'Trust Position',
                        labelHE: 'עמדת הקרן הנאמנות',
                        icon: 'fe-percent',
                        link: '/operator/platform-analytics/trust-position',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        hasChildren: false,
                        show: false,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "fund",
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-unit-funding',
                        label: 'Unit Funding',
                        labelHE: 'מימון ע״י יחידות השתתפות',
                        icon: 'fe-bar-chart',
                        link: '/operator/platform-analytics/unit-funding/summary',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        show: false,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "fund",
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-fund-position',
                        label: 'Fund Position',
                        labelHE: 'עמדת הקרן ההשקעות',
                        icon: 'fe-dollar-sign',
                        link: '/operator/platform-analytics/fund-position',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        show: false,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "fund",
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-',
                        label: 'E2E Network allocations',
                        labelHE: 'הקצאות רשת קצה-אל-קצה',
                        icon: 'fe-hash',
                        link: '/operator/platform-analytics/end-to-end-allocationss',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        show: false,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "fund",
                    },
                ]
            },
            {
                key: 'operator-financial-analytics-platform-analysis-underwriting-analyses',
                label: 'Underwriting',
                labelHE: 'חיתום',
                icon: 'dripicons dripicons-crosshair',
                // link: '/member/requests/loans',
                parentKey: 'operator-financial-analytics',
                collapsed: true,
                show: false,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "assets",
                children: [

                    {
                        key: 'operator-financial-analytics-platform-analysis-underwriting-analyses-underwriting-dashboard',
                        label: 'Underwriting Dashboard',
                        labelHE: 'דַּשְׁבּוֹרְד חיתום',
                        parentKey: 'operator-financial-analytics-platform-analysis-underwriting-analyses',
                        icon: 'fe-airplay',
                        show: true,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "assets",
                        link: '/analysis/network/dashboard/id/underwriting'
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-lending-analysis',
                        // label: 'Loan Portfolio',
                        label: 'Loan Asset Network Analysis',
                        labelHE: 'דַּשְׁבּוֹרְד ניתוחי רשת',
                        // icon: 'dripicons dripicons-network-3',
                        link: '/operator/platform-analytics/loan-underwriting',
                        parentKey: 'operator-financial-analytics-platform-analysis',
                        show: true,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "assets",
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-underwriting-analyses-loan-origination',
                        label: 'Loan Origination',
                        labelHE: 'יצירת הלוואות',
                        // icon: 'dripicons dripicons-network-3',
                        parentKey: 'operator-financial-analytics-platform-analysis-underwriting-analyses',
                        show: true,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "assets",
                        link: '/analysis/loan/underwriting/analysis/id'
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-underwriting-analyses-loan-sale',
                        label: 'Loan Sale',
                        labelHE: 'מכירת הלוואות',
                        // icon:'fe-dollar-sign',
                        parentKey: 'operator-financial-analytics-platform-analysis-underwriting-analyses',
                        show: true,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "assets",
                        link: '/operator/platform-analytics/loan-underwriting-sales'
                        // link: '/analysis/underwriting/loan-sale/id'
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-underwriting-analyses-p-notes',
                        label: 'P-Notes',
                        labelHE: 'P-Notes',
                        // icon: 'dripicons dripicons-graph-line',
                        parentKey: 'operator-financial-analytics-platform-analysis-underwriting-analyses',
                        show: true,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "marketplace",
                        link: '/analysis/underwriting/p-note/id'
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-underwriting-analyses-s-notes',
                        label: 'S-Notes',
                        labelHE: 'S-Notes',
                        // icon:'fe-bar-chart-2',
                        parentKey: 'operator-financial-analytics-platform-analysis-underwriting-analyses',
                        show: true,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "securitization",
                        link: '/analysis/underwriting/s-note/id'
                    },
                    {
                        key: 'operator-financial-analytics-platform-analysis-underwriting-analyses-fund-units',
                        label: 'Fund Units',
                        labelHE: 'יחידות השתתפות',
                        // icon: 'fe-percent',
                        parentKey: 'operator-financial-analytics-platform-analysis-underwriting-analyses',
                        show: false,
                        isInternal: true,
                        isMember: false,
                        isProduct: false,
                        product: "fund",
                        link: '/analysis/underwriting/fund-unit/id'
                    }
                ]
            },
            {
                key: 'operator-financial-analytics-platform-analysis-risk-engine-analyses',
                label: 'Risk Engine Analyses',
                labelHE: 'ניתוחי מנועת הסיכונים',
                icon: 'dripicons dripicons-suitcase',
                link: '/operator/platform-analytics/risk/tickets',
                parentKey: 'operator-financial-analytics',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",
            },
            {
                key: 'operator-financial-analytics-platform-analysis-member-analytics',
                label: 'Member Analytics',
                labelHE: 'ניתוחי עמיתים',
                icon: 'dripicons dripicons-graph-bar',
                link: '/operator/member-analytics/member-analytics-dashboard',
                parentKey: 'operator-financial-analytics',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",
                collapsed: true,

            }
        ]

    },
]

const MENU_ITEMS_INS_PRODUCTS_OPERATOR_ADMINISTRATION: MenuItem[] = [
    {
        key: 'operator-administration',
        label: 'Administration',
        labelHE: 'אדמיניסטרציה',
        isTitle: false,
        icon: 'dripicons dripicons-archive',
        link: '/operator/dashboard',
        collapsed: true,
        show: true,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "all",
        children: [
            {
                key: 'operator-administration-activity',
                label: 'Activity & Workflows',
                labelHE: 'פעולות ופעילות',
                icon: 'fe-activity',
                link: '/operator/administration/activity',
                parentKey: 'operator-administration',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",
            },

            {
                key: 'operator-administration-templates',
                label: 'Models & Templates',
                labelHE: 'תבניות',
                icon: 'fe-copy',
                link: '/operator/administration/templates',
                parentKey: 'operator-administration',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",
            },
            {
                key: 'operator-administration-documents',
                label: 'Documents',
                labelHE: 'מסמכים',
                icon: 'dripicons dripicons-folder-open',
                link: '/operator/administration/documents',
                parentKey: 'operator-administration',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",
            },
            {
                key: 'operator-administration-communications',
                label: 'Communications',
                labelHE: 'התקשרויות',
                icon: 'fas fa-envelope-open-text',
                link: '/operator/administration/communications',
                parentKey: 'operator-administration',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",

            },
            {
                key: 'operator-administration-calendar',
                label: 'Calendar',
                labelHE: 'יומן',
                icon: 'far fa-calendar',
                link: '/operator/administration/calendar',
                parentKey: 'operator-administration',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",

            },
            {
                key: 'operator-administration-helpdesk',
                label: 'Helpdesk',
                labelHE: 'מוקד תמיכה',
                icon: 'fe-help-circle',
                link: '/operator/administration/helpdesk',
                parentKey: 'operator-administration',
                show: false,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",

            },
        ]

    },
]

const MENU_ITEMS_INS_PRODUCTS_OPERATOR_TECH_OPERATIONS: MenuItem[] = [
    {
        key: 'operator-tech-operations',
        label: 'Tech Operations',
        labelHE: 'תפעול טכני',
        icon: 'fe-box',
        // link: '/operator/dashboard',
        isTitle: false,
        show: true,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "all",
        collapsed: true,
        children: [
            {
                key: 'operator-administration-dashboard',
                label: 'Dashboard',
                labelHE: 'תבניות',
                icon: 'fe-airplay',
                link: '/operator/administration/dashboard',
                parentKey: 'operator-administration',
                show: true,
                isInternal: true,
                isMember: false,
                isProduct: false,
                product: "all",
            },
            {
                label: 'Core Banking',
                labelHE: 'בנקאות',
                key: 'operator-tech-operations-core-banking',
                icon: 'mdi mdi-bank',
                parentKey: 'operator-tech-operations',
                show: true,
                isInternal: false,
                isLink: true,
                isMember: false,
                isProduct: false,
                product: "all",
            },
            {
                label: 'Smart Contracting',
                labelHE: 'חוזים חכמים',
                key: 'operator-tech-operations-smart-contracting',
                icon: 'dripicons dripicons-network-3',
                parentKey: 'operator-tech-operations',
                show: false,
                isInternal: false,
                isMember: false,
                isProduct: false,
                product: "all",
                isLink: true,
            },
            {
                label: 'Workflows',
                labelHE: 'תהליכי פעולי',
                key: 'operator-tech-operations-workflow',
                icon: 'dripicons dripicons-media-shuffle',
                isTitle: false,
                collapsed: true,
                show: true,
                isInternal: false,
                isMember: false,
                isProduct: false,
                product: "all",
                parentKey: 'operator-tech-operations',
                children: [
                    {
                        key: 'operator-tech-operations-workflow-idm',
                        label: 'IDM',
                        labelHE: 'IDM',
                        // icon: 'fe-none_inbox', 
                        parentKey: 'operator-tech-operations-workflow',
                        show: true,
                        isInternal: false,
                        isLink: true,
                        isMember: false,
                        isProduct: false,
                        product: "all",
                    },
                    {
                        key: 'operator-tech-operations-workflow-admin',
                        label: 'Admin',
                        labelHE: 'Admin',
                        // icon: 'fe_golf_course', 
                        parentKey: 'operator-tech-operations-workflow',
                        show: true,
                        isInternal: false,
                        isLink: true,
                        isMember: false,
                        isProduct: false,
                        product: "all",
                    },
                    {
                        key: 'operator-tech-operations-workflow-admin',
                        label: 'Modeler',
                        labelHE: 'Modeler',
                        // icon: 'fe_query_builder', 
                        parentKey: 'operator-tech-operations-workflow',
                        show: true,
                        isInternal: false,
                        isLink: true,
                        isMember: false,
                        isProduct: false,
                        product: "all",
                    },
                    {
                        key: 'operator-tech-operations-workflow-task',
                        label: 'Tasks',
                        labelHE: 'Tasks',
                        // icon: 'bathtub', 
                        parentKey: 'operator-tech-operations-workflow',
                        show: true,
                        isInternal: false,
                        isLink: true,
                        isMember: false,
                        isProduct: false,
                        product: "all",

                    }
                ]
            },
            {
                key: 'operator-tech-operations-relationship-management-crm',
                label: 'CRM',
                labelHE: 'CRM',
                icon: 'dripicons-web',
                show: true,
                parentKey: 'operator-tech-operations-relationship-management',
                isInternal: false,
                isMember: false,
                isProduct: false,
                product: "all",
                isLink: true,
            },

        
            {
                label: 'APIs',
                labelHE: 'ממשקי API',
                icon: 'dripicons-code',
                parentKey: 'operator-tech-operations-apis',
                isTitle: false,
                show: true,
                isInternal: false,
                isMember: false,
                isProduct: false,
                product: "all",
                collapsed: true,
                children: [
                    {
                        label: 'Registry',
                        labelHE: 'Registry',
                        key: 'operator-tech-operations-apis-registry',
                        // icon: 'fas fa-registered', 
                        parentKey: 'operator-tech-operations-apis',
                        show: true,
                        isInternal: false,
                        isLink: true,
                        isMember: false,
                        isProduct: false,
                        product: "all",
                    },
                    {
                        key: 'operator-tech-operations-apis-dlt',
                        label: 'DLT',
                        labelHE: 'DLT',
                        // icon: 'dripicons-pulse', 
                        parentKey: 'operator-tech-operations-api',
                        show: true,
                        isInternal: false,
                        isLink: true,
                        isMember: false,
                        isProduct: false,
                        product: "all",
                    },
                    {
                        label: 'InState',
                        labelHE: 'InState',
                        key: 'operator-tech-operations-apis-api',
                        // icon: 'dripicons-pulse', 
                        parentKey: 'operator-tech-operations-apis',
                        show: true,
                        isInternal: false,
                        isLink: true,
                        isMember: false,
                        isProduct: false,
                        product: "all",
                    },


                ]
            },
            {
                label: 'Infrastructure',
                labelHE: 'Infrastructure',
                icon: 'dripicons-cloud',
                parentKey: 'operator-tech-operations',
                key: 'operator-tech-operations-infrastructure',
                isTitle: true,
                show: true,
                isInternal: false,
                isMember: false,
                isProduct: false,
                product: "all",
                collapsed: true,
                children: [
                    {
                        label: 'Dashboard',
                        labelHE: 'Dashboard',
                        key: 'operator-tech-operations-infrastructure-graphna',
                        icon: 'fe-airplay',
                        parentKey: 'operator-tech-operations-infrastructure',
                        show: true,
                        isInternal: false,
                        isLink: true,
                        isMember: false,
                        isProduct: false,
                        product: "all",
                    },

                    {
                        label: 'Monitoring',
                        labelHE: 'Monitoring',
                        key: 'operator-tech-operations-infrastructure-prometheus',
                        // icon: 'fas fa-registered', 
                        parentKey: 'operator-tech-operations-infrastructure-infrastructure',
                        show: true,
                        isInternal: false,
                        isLink: true,
                        isMember: false,
                        isProduct: false,
                        product: "all",
                    },
                    {
                        label: 'Alerts',
                        labelHE: 'Alerts',
                        key: 'operator-tech-operations-infrastructure-alerts',
                        // icon: 'fas fa-registered', 
                        parentKey: 'operator-tech-operations-infrastructure',
                        show: true,
                        isInternal: false,
                        isLink: true,
                        isMember: false,
                        isProduct: false,
                        product: "all",
                    },
                    {
                        label: 'Control',
                        labelHE: 'Control',
                        key: 'operator-tech-operations-infrastructure-supervisor',
                        // icon: 'fas fa-registered', 
                        parentKey: 'operator-tech-operations-monitoring-infrastructure',
                        show: true,
                        isInternal: false,
                        isLink: true,
                        isMember: false,
                        isProduct: false,
                        product: "all",
                    },




                ]
            },
        ]


    },
]


// menu items for vertcal and detached layout
const MENU_ITEMS_INS_PRODUCTS_OPERATOR: MenuItem[] = [
    ...MENU_ITEMS_INS_PRODUCTS_OPERATOR_TOP_LEVEL,
    {
        key: 'operator-dlt-network-analysis-home',
        label: 'Network Analysis',
        labelHE: 'דַּשְׁבּוֹרְד אנליטיקה של הרשת',
        // icon: 'dripicons dripicons-network-3',
        icon: 'fe-airplay',
        link: '/operator/platform-analytics/network-analysis-dashboard',
        // parentKey: 'operator-credit-network',
        show: false,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "assets",
    },
    {
        key: 'operator-marketplace',
        label: 'Marketplace',
        labelHE: 'רשת אשראי',
        isTitle: false,
        collapsed: true,
        icon: 'dripicons dripicons-store',
        link: '/operator/marketplaces/investments',
        show: true,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "marketplace",

    },
    ...MENU_ITEMS_INS_PRODUCTS_OPERATOR_PRODUCT_MANAGEMENT,
    ...MENU_ITEMS_INS_PRODUCTS_OPERATOR_CORE_ACCOUNTING,
    ...MENU_ITEMS_INS_PRODUCTS_OPERATOR_FINANCIAL_ANALYTICS,
    ...MENU_ITEMS_INS_PRODUCTS_OPERATOR_ADMINISTRATION,
    ...MENU_ITEMS_INS_PRODUCTS_OPERATOR_TECH_OPERATIONS
];


const MENU_ITEMS_INS_PRODUCTS_MEMBER_TOP_LEVEL: MenuItem[] = [

    {
        key: 'member',
        label: 'Member Menu',
        labelHE: 'תפריט עמיתים',
        isTitle: true,
        show: true,
        isInternal: true,
        isMember: false,
        isProduct: false,
        product: "all",

    },

    {
        key: 'member-home',
        label: 'Home',
        labelHE: 'בית',
        isTitle: false,
        icon: 'fas fa-home',
        link: '/member/dashboard',
        show: true,
        isInternal: true,
        isMember: true,
        isProduct: false,
        product: "all",
    },
    {
        key: 'member-position',
        label: 'My Tokens',
        labelHE: 'עמדה שלי ברשת',
        isTitle: false,
        icon: 'dripicons-crosshair',
        link: '/member/position/dashboard',
        show: true,
        isInternal: true,
        isMember: true,
        isProduct: false,
        product: "all",
    },
   
  


];

const MENU_ITEMS_INS_PRODUCTS_MEMBER_MID_LEVEL: MenuItem[] = [

  
    {
        key: 'member-marketplace',
        label: 'Marketplace',
        labelHE: 'רשת אשראי',
        isTitle: false,
        collapsed: true,
        icon: 'dripicons-store',
        link: '/member/marketplaces/investments',
        show: true,
        isInternal: true,
        isMember: true,
        isProduct: true,
        product: "marketplace",

    },
    {
        key: 'member-requests-and-quotes-all',
        label: 'Requests',
        labelHE: 'אונבורדינג',
        icon: 'fas fa-concierge-bell',
        link: '/member/requests/all',
        // parentKey: null,
        show: true,
        isInternal: true,
        isMember: true,
        isProduct: false,
        product: "all",
    },
  


];


const MENU_ITEMS_INS_PRODUCTS_MEMBER_ACCOUNTS: MenuItem[] = [
    {
        key: 'member-accounts',
        label: 'My Wallet',
        labelHE: 'חשבונות',
        isTitle: false,
        collapsed: true,
        isMember: true,
        isProduct: false,
        product: "wallet",
        show: true,
        icon: 'fas fa-balance-scale',
        children: [
            {
                key: 'member-accounts-dashboard',
                label: 'Dashboard ',
                labelHE: 'דשבורד חשבונות',
                link: '/member/accounts/dashboard',
                // icon: 'fas fa-balance-scale',
                icon: 'fe-airplay',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                // icon: 'fas fa-balance-scale',
                product: "wallet",

            },
            {
                key: 'member-accounts-wallet',
                label: 'Cash',
                labelHE: 'ארנק',
                link: '/member/accounts/cash',
                parentKey: 'member-accounts',
                show: true,
                isInternal: true,
                icon: 'fas fa-wallet noti-icon',
                isMember: true,
                isProduct: false,
                product: "wallet",
            },

            {
                key: 'member-accounts-investments',
                label: 'Investments',
                labelHE: 'השקעות',
                link: '/member/accounts/investments',
                icon: 'mdi mdi-signal-cellular-outline',
                parentKey: 'member-accounts',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "marketplace",
            },



        ],


    },

   



];

const MENU_ITEMS_INS_PRODUCTS_MEMBER_ACCOUNTS_SEED: MenuItem[] = [
    {
        key: 'member-accounts',
        label: 'My Wallet',
        labelHE: 'חשבונות',
        isTitle: false,
        collapsed: true,
        isMember: true,
        isProduct: false,
        product: "wallet",
        show: true,
        icon: 'fas fa-balance-scale',
        children: [
            {
                key: 'member-accounts-dashboard',
                label: 'Dashboard ',
                labelHE: 'דשבורד חשבונות',
                link: '/member/accounts/dashboard',
                // icon: 'fas fa-balance-scale',
                icon: 'fe-airplay',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                // icon: 'fas fa-balance-scale',
                product: "wallet",

            },
            {
                key: 'member-accounts-wallet',
                label: 'Cash',
                labelHE: 'ארנק',
                link: '/member/accounts/cash',
                parentKey: 'member-accounts',
                show: true,
                isInternal: true,
                icon: 'fas fa-wallet noti-icon',
                isMember: true,
                isProduct: false,
                product: "wallet",
            },
            {
                key: 'member-accounts-loans',
                label: 'Tokenized Loans',
                labelHE: 'הלוואות',
                link: '/member/accounts/tokenized-loans',
                parentKey: 'member-accounts',
                icon: 'fas fa-hand-holding-usd',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "assets",
            },
            {
                key: 'member-accounts-loans',
                label: 'Invoices',
                labelHE: 'חשבוניות',
                link: '/member/accounts/invoices',
                // icon: 'fas fa-hand-holding-usd',
                parentKey: 'member-accounts',
                isTitle: false,
                show: false,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "assets",
            },
            {
                key: 'member-accounts-investments',
                label: 'Investments',
                labelHE: 'השקעות',
                link: '/member/accounts/investments',
                icon: 'mdi mdi-signal-cellular-outline',
                parentKey: 'member-accounts',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "marketplace",
            },



        ],


    },

   



];

const MENU_ITEMS_INS_PRODUCTS_MEMBER_ANALYTICS: MenuItem[] = [

    {
        key: 'member-analytics',
        label: 'Analytics',
        labelHE: 'אנליטיקה',
        isTitle: false,
        collapsed: true,
        link: '/member/analytics/dashboard',
        show: true,
        isInternal: true,
        isMember: true,
        isProduct: false,
        product: "assets",
        icon: 'fe-airplay',
    },
    {
        key: 'member-analytics',
        label: 'Analytics',
        labelHE: 'אנליטיקה',
        isTitle: false,
        collapsed: true,
        show: false,
        isInternal: true,
        isMember: true,
        isProduct: false,
        product: "assets",
        icon: 'dripicons dripicons-graph-pie',
        children: [
            {
                key: 'member-analytics-dashboard',
                label: 'Analytics Dashboard',
                labelHE: 'דשבורד אנליטיקה',
                link: '/member/analytics/dashboard',
                parentKey: 'member-analytics',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "assets",
                icon: 'fe-airplay',
            },
            {
                key: 'member-analytics-lender-analysis',
                label: 'Lender Credit Portfolio',
                labelHE: 'תיק אשראי של מלווה',
                link: '/member/analytics/lender/id',
                parentKey: 'member-analytics',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "assets",
            },
            {
                key: 'member-analytics-business-analysis',
                label: 'Business Financials',
                labelHE: 'ניתוחים פיננסים של עסקים',
                link: '/member/analytics/business',
                parentKey: 'member-analytics',
                show: false,
                isInternal: false,
                isMember: true,
                isProduct: false,
                product: "all",
            },
            {
                key: 'member-analytics-portfolio-analysis',
                label: 'Investor Portfolio',
                labelHE: 'ניתוחי תיקי השקעות',
                link: '/member/analytics/portfolio',
                parentKey: 'member-analytics',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "all",
            },


        ],


    },

];


const MENU_ITEMS_INS_PRODUCTS_MEMBER_ADMIN: MenuItem[] = [

    {
        key: 'member-administration',
        label: 'Administration',
        labelHE: 'אדמיניסטרציה',
        isTitle: false,
        collapsed: true,
        icon: 'dripicons dripicons-archive',
        show: true,
        isInternal: true,
        isMember: true,
        isProduct: false,
        product: "all",
        children: [
            {
                key: 'member-administration-profile-preferences',
                label: 'Profile and Preferences',
                labelHE: 'פרופיל והעדפות',
                link: '/member/administration/profile_and_preferences',
                parentKey: 'member-administration',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "all",
            },
            {
                key: 'member-administration-activity',
                label: 'Actions and Activity',
                labelHE: 'פעולות ופעילות',
                link: '/member/administration/activity',
                parentKey: 'member-administration',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "all",
            },
            {
                key: 'member-administration-documents',
                label: 'Documents',
                labelHE: 'מסמכים',
                link: '/member/administration/documents',
                parentKey: 'member-administration',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "all",
            },
            {
                key: 'member-administration-communications',
                label: 'Communications',
                labelHE: 'התקשרויות',
                link: '/member/administration/communications',
                parentKey: 'member-administration',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "all",
            },
            {
                key: 'member-administration-calendar',
                label: 'Calendar',
                labelHE: 'יומן',
                link: '/member/administration/calendar',
                parentKey: 'member-administration',
                show: true,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "all",
            },
            {
                key: 'member-administration-tickets',
                label: 'Helpdesk',
                labelHE: 'מוקד תמיכה',
                link: '/member/administration/tickets',
                parentKey: 'member-administration',
                show: false,
                isInternal: true,
                isMember: true,
                isProduct: false,
                product: "all",
            },



        ],


    },

];

const MENU_ITEMS_INS_PRODUCTS_MEMBER: MenuItem[] = [
    ...MENU_ITEMS_INS_PRODUCTS_MEMBER_TOP_LEVEL,
    ...MENU_ITEMS_INS_PRODUCTS_MEMBER_ACCOUNTS,
    ...MENU_ITEMS_INS_PRODUCTS_MEMBER_MID_LEVEL,
    ...MENU_ITEMS_INS_PRODUCTS_MEMBER_ADMIN
];

const MENU_ITEMS_INS_PRODUCTS_MEMBER_SEED: MenuItem[] = [
    ...MENU_ITEMS_INS_PRODUCTS_MEMBER_TOP_LEVEL,
    ...MENU_ITEMS_INS_PRODUCTS_MEMBER_ACCOUNTS_SEED,
    ...MENU_ITEMS_INS_PRODUCTS_MEMBER_MID_LEVEL,
    ...MENU_ITEMS_INS_PRODUCTS_MEMBER_ANALYTICS,
    ...MENU_ITEMS_INS_PRODUCTS_MEMBER_ADMIN
];


const MENU_ITEMS_INS_PRODUCTS: MenuItem[] = [
    ...MENU_ITEMS_INS_PRODUCTS_OPERATOR,
    ...MENU_ITEMS_INS_PRODUCTS_MEMBER

];

const MENU_ITEMS_INS_PRODUCTS_SEED: MenuItem[] = [
    ...MENU_ITEMS_INS_PRODUCTS_OPERATOR,
    ...MENU_ITEMS_INS_PRODUCTS_MEMBER_SEED

];



export { 
    MENU_ITEMS_INS_PRODUCTS,
    MENU_ITEMS_INS_PRODUCTS_SEED 

};
